name: Clean and Reorganize Previous Solutions

# A MÁGICA ESTÁ AQUI: Este workflow só roda quando você clica no botão.
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mover todas as soluções antigas para a raiz
        run: |
          echo "Iniciando a movimentação de todas as soluções para a raiz..."
          set -x # Ativa o modo debug para vermos tudo que acontece

          # Percorre todas as pastas de linguagem e dificuldade
          for lang in SQL Python CSharp; do
            for diff in Easy Medium Hard; do
              path="$lang/$diff"
              # Verifica se o diretório existe (ex: Python/Easy)
              if [ -d "$path" ]; then
                # Move cada pasta de solução dentro dele para a raiz
                for solution_dir in "$path"/*/; do
                  if [ -d "$solution_dir" ]; then
                    echo "Movendo $(basename "$solution_dir") para a raiz..."
                    # Usa git mv para mover a pasta para o diretório atual (./)
                    git mv "$solution_dir" ./
                  fi
                done
              fi
            done
          done
          
          echo "Movimentação concluída."

      - name: Commit and Push a preparação para reorganização
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Verifica se houve alguma movimentação de arquivo
          if ! git diff --staged --quiet; then
            echo "Soluções movidas para a raiz. Commitando a preparação..."
            git commit -m "chore(cleanup): prepare all solutions for re-organization"
            git pull --rebase
            git push
          else
            echo "Nenhuma solução antiga encontrada para mover."
          fi
