name: Organize LeetCode Solutions

on:
  push:
    branches:
      - main

jobs:
  organize:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão necessária para fazer push

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para o git ter o histórico completo

      - name: Organize solutions into language and difficulty directories
        run: |
          # 1. Cria os diretórios de destino para evitar erros
          for lang in SQL Python CSharp; do
            mkdir -p "$lang/Easy" "$lang/Medium" "$lang/Hard"
          done

          # 2. Percorre cada pasta de problema na raiz
          for problem_dir in */; do
            # Ignora pastas de configuração e as de destino
            if [[ "$problem_dir" == ".git/" || "$problem_dir" == ".github/" || "$problem_dir" == "SQL/" || "$problem_dir" == "Python/" || "$problem_dir" == "CSharp/" ]]; then
              continue
            fi
            
            base_name=$(basename "$problem_dir")
            echo "Processing: $base_name"

            # 3. EXTRAI A DIFICULDADE do README.md
            readme_file="${problem_dir}README.md"
            difficulty="" # Reseta a variável
            if [[ -f "$readme_file" ]]; then
              # Procura pela string 'Difficulty-Easy', 'Difficulty-Medium', etc. e extrai a dificuldade
              difficulty=$(grep -o 'Difficulty-[^']+' "$readme_file" | head -n 1 | cut -d'-' -f2)
              if [[ -n "$difficulty" ]]; then
                echo "  - Difficulty found: $difficulty"
              else
                echo "  - Difficulty not found in README. Skipping."
                continue
              fi
            else
              echo "  - README.md not found. Skipping."
              continue
            fi

            # 4. Verifica o tipo de arquivo e move a pasta para o destino correto
            destination_path=""
            if ls "${problem_dir}"*.sql 1> /dev/null 2>&1; then
              destination_path="SQL/${difficulty}"
            elif ls "${problem_dir}"*.py 1> /dev/null 2>&1; then
              destination_path="Python/${difficulty}"
            elif ls "${problem_dir}"*.cs 1> /dev/null 2>&1; then
              destination_path="CSharp/${difficulty}"
            fi

            # 5. Move a pasta se um destino válido foi encontrado
            if [[ -n "$destination_path" ]]; then
              echo "  - Moving to ${destination_path}/"
              # Cria o diretório de destino final, caso ainda não exista
              mkdir -p "${destination_path}"
              # Move a pasta usando git mv para manter o histórico
              git mv "${problem_dir}" "${destination_path}/"
            fi
          done

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add -A

          # Verifica se há alguma mudança para commitar
          if ! git diff --staged --quiet; then
            echo "Changes found. Committing and pushing..."
            git commit -m "chore(auto): organize solutions into difficulty folders"
            git pull --rebase
            git push
          else
            echo "No changes to commit."
          fi
