- name: Organizar, Contar e Atualizar README
        run: |
          echo "Iniciando processo completo..."
          set -x

          # --- PARTE 1: ORGANIZAR PASTAS ---
          # (Esta parte está perfeita, não precisa mudar)
          for problem_dir in */; do
            if [[ "$problem_dir" == ".git/" || "$problem_dir" == ".github/" || "$problem_dir" == "SQL/" || "$problem_dir" == "Python/" || "$problem_dir" == "CSharp/" ]]; then
              continue
            fi
            base_name=$(basename "$problem_dir")
            readme_file="${problem_dir}README.md"
            difficulty=""
            if [[ -f "$readme_file" ]]; then
              difficulty_line=$(grep -o 'Difficulty-Easy\|Difficulty-Medium\|Difficulty-Hard' "$readme_file" | head -n 1)
              if [[ -n "$difficulty_line" ]]; then
                difficulty=$(echo "$difficulty_line" | cut -d'-' -f2)
              else
                continue
              fi
            else
              continue
            fi
            destination_path=""
            if ls "${problem_dir}"*.sql 1> /dev/null 2>&1; then
              destination_path="SQL/${difficulty}"
            elif ls "${problem_dir}"*.py 1> /dev/null 2>&1; then
              destination_path="Python/${difficulty}"
            elif ls "${problem_dir}"*.cs 1> /dev/null 2>&1; then
              destination_path="CSharp/${difficulty}"
            fi
            if [[ -n "$destination_path" ]]; then
              mkdir -p "${destination_path}"
              git mv "${problem_dir}" "${destination_path}/"
            fi
          done

          # --- PARTE 2: CONTAR SOLUÇÕES ---
          # (Esta parte está perfeita, não precisa mudar)
          EASY_COUNT=$( (find SQL/Easy Python/Easy CSharp/Easy -mindepth 1 -maxdepth 1 -type d 2>/dev/null || true) | wc -l)
          MEDIUM_COUNT=$( (find SQL/Medium Python/Medium CSharp/Medium -mindepth 1 -maxdepth 1 -type d 2>/dev/null || true) | wc -l)
          HARD_COUNT=$( (find SQL/Hard Python/Hard CSharp/Hard -mindepth 1 -maxdepth 1 -type d 2>/dev/null || true) | wc -l)
          TOTAL_COUNT=$((EASY_COUNT + MEDIUM_COUNT + HARD_COUNT))
          CURRENT_DATE=$(date +"%Y-%m-%d")

          # --- PARTE 3: ATUALIZAR O README (COM A CORREÇÃO) ---
          echo "Atualizando README.md com padrão seguro..."
          # A CORREÇÃO ESTÁ AQUI: Trocamos o '.*' ganancioso por '[^<]*'
          sed -i "s|[^<]*|${EASY_COUNT}|g" README.md
          sed -i "s|[^<]*|${MEDIUM_COUNT}|g" README.md
          sed -i "s|[^<]*|${HARD_COUNT}|g" README.md
          sed -i "s|[^<]*|${TOTAL_COUNT}|g" README.md
          sed -i "s|[^<]*|${CURRENT_DATE}|g" README.md
